### ISSUE TITLE
Satellizer only saving one user, then no more

### ISSUE THREAD

**Issue by kmaida** [sahat/satellizer#332]
Hello, I'm having a concern wherein ONLY the first user seems to be saving to MongoDB. If the collection is empty, the first account to sign in will save. However, nothing else saves to the database after that. If I drop that document, then I can save the next one but only one can ever exist in the database at a time.

I'm using node and mongo, and am using the node server.js settings from the Satellizer repo's examples. I have Google, Twitter, Facebook, and GitHub integrations. They all "appear" to work (as in, I can log in and out with them), except no records (apart from that first one) ever save to Mongo. I realized this was happening when `/api/me` was failing for everything except for one account, which was determined to be the sole account that successfully made it into the database.

I've tried this on local databases as well as MongoLab with the same results.

When I try to write to the database from the shell manually after there is a document in it, I get an `11000 duplicate key` error.

Do you have any advice or insight? Is this caused by the way the node server.js example is set up? Hitting Google has had me coming up with a lot of nothing.

Thank you so much for any thoughts on this!

**Comment by kmaida** [comment]
As a side note, it seems that Google is the only one actually saving data to the database (I'm using Node and MongoDB, my server code is using the Node example in the Satellizer examples). Twitter, Facebook, and GitHub logins "work" but they don't create entries in Mongo. I'm not sure if this issue is completely separate or if it's in any way related to this one (`/api/me` doesn't work with any of the above).

**Comment by kmaida** [comment]
I've fixed this. I had to deal with unique and duplicates in MongoDB. Not actually a Satellizer issue; closing.

**Comment by DonLiborio** [comment]
Hi Kim. I'm having the same issue as you describe here.

I'm just trying to get the provided nodejs demo to work. I've minimally modified the "server.js" file to make it work on openshift. But I'm still having this issue, only one record gets saved in mongo. Do you remember how you fixed it?

I'm not a programmer, I'm a musician struggling to get authentication to work for my site. This is hard for me! :)

**Comment by DonLiborio** [comment]
Well, it's weird. For some reason the "users" collection in mongo didn't allow new records. As soon as I deleted the collection, everything started to work again, and I can have multiple users. Your issue allowed me to find a fix, though. Thanks!

**Comment by kmaida** [comment]
Glad you were able to get it resolved! Definitely a database issue though.

**Comment by andjosaquino** [comment]
@kmaida  and @DonLiborio  Hey, I am getting the same issue, do either of you mind explaining what solution you did? Thanks :C.
